services:
  mysql:
    image: mysql:8.0
    container_name: basededatos-container
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "monitoreo_db"
      MYSQL_USER: "kelly"
      MYSQL_PASSWORD: "1234"
    volumes:
      - mysql-db:/var/mysql      # Volumen persistente para los datos
      - ./Script.sql:/docker-entrypoint-initdb.d/Script.sql  # Montar el archivo Script.sql
    ports:
      - "3306:3306"
  node-app:
    image: "kelly901/image_node:v3"
    #build: ../Backend/ApiNode
    container_name: container-node
    ports:
     - "5002:5002"
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"  # Exposes Grafana's web interface on localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password (change it in production)
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana data
    depends_on:
      - mysql
    restart: unless-stopped


volumes:
  mysql-db: # Volumen persistente para MySQL
  grafana_data:
