services:
  mysql:
    image: mysql:8.0
    container_name: basededatos-container
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "monitoreo_db"
      MYSQL_USER: "kelly"
      MYSQL_PASSWORD: "1234"
    volumes:
      - mysql-db:/var/mysql      # Volumen persistente para los datos
      - ./Script.sql:/docker-entrypoint-initdb.d/Script.sql  # Montar el archivo Script.sql
    ports:
      - "3306:3306"
  node-app:
    image: "kelly901/image_node:v3"
    #build: ../Backend/ApiNode
    container_name: container-node
    ports:
     - "5002:5002"
    restart: always
  #my-go-app:
   #image: "kelly901/image_go:v3"
   #container_name: "backend_go" 
   #ports:
   #  - "5200:5200"
   #restart: always

volumes:
  mysql-db: # Volumen persistente para MySQL

